### ISSUE TITLE
Improve GTT Export screen layout

### ISSUE THREAD

**Issue by sanak** [gtt-project/smash_import_export_plugins#11]
**Problem**
Currently, `GTT Export` screen layout is a bit narrow and word wrap happens at left label (data type: data amount) part.
<img width="356" alt="smash-gtt-export-form-layout" src="https://user-images.githubusercontent.com/629923/188248977-09321fd0-e3a1-4613-a159-63e3ab742963.png">

**Improvement**
It will be good to improve this screen more understandable.

**Comment by sanak** [comment]
@Tannybunny (CC: @nobnisai, @mbasa-georepublic, @dkastl)
I am thinking that the following **`New`** changes will be better, but how do you think about this ?

### Current

<table>
  <tbody>
    <tr>
      <td colspan=2 align=left>←　　GTT Export</td>
    </tr>
    <tr>
      <td colspan=2 align=center><b>Sync Stats</b></td>
    </tr>
    <tr>
      <td colspan=2 align=left>The following data will be uploaded only if the project is <br>selected.</td>
    </tr>
    <tr>
      <td colspan=2 align=center>No Available Project, Contact your admin.</td>
    </tr>
    <tr>
      <td>Gps logs: 0</td><td align=right>Select Project　　　　　▼</td>
    </tr>
    <tr>
      <td>Simple Notes: <br>0</td><td align=right>Select Project　　　　　▼</td>
    </tr>
    <tr>
      <td>Images: 0</td><td align=right>Select Project　　　　　▼</td>
    </tr>
    <tr>
      <td colspan=2>Form Notes: 1</td>
    </tr>
    </tr>
  </tbody>
</table>

### New

<table>
  <tbody>
    <tr>
      <td colspan=2 align=left>←　　GTT Export</td>
    </tr>
    <tr>
      <td colspan=2 align=center><b>Sync Stats</b></td>
    </tr>
    <tr>
      <td colspan=2 align=left>The following data will be uploaded only if the project is <br>selected. If there is no available project, please contact <br>your admin.</td>
    </tr>
    <tr>
      <td colspan=2>Form Notes: 1</td>
    </tr>
    <tr>
      <td colspan=2>Gps logs: 0</td>
    </tr>
    <tr>
      <td></td><td align=right>Select Project　　　　　▼</td>
    </tr>
    <tr>
      <td colspan=2>Simple Notes: 0</td>
    </tr>
    <tr>
      <td></td><td align=right>Select Project　　　　　▼</td>
    </tr>
    <tr>
      <td colspan=2>Images: 0</td>
    </tr>
    <tr>
      <td></td><td align=right>Select Project　　　　　▼</td>
    </tr>
    </tr>
  </tbody>
</table>

#### Summary

1. Concatenate sentences below **`Sync Stats`**.
2. Move bottom `Form Notes: n` to top.
3. Split other items from 1 row to 2 rows with keeping `Select Project` dropdown align=right.

**Comment by Tannybunny** [comment]
I think it is a good idea to have only one column. But I would left align everything so it looks more organized and use spacing between each group so it's easier to identify what belongs together.
Here is a quick sketch from photoshop just to illustrate what I mean
![image](https://user-images.githubusercontent.com/51223963/189861532-83040d7d-1b54-4715-b312-26194cdb0efa.png)

**Comment by sanak** [comment]
@Tannybunny Okay, thanks for quick fix!
I think that it's better than mine. 👍😄

@nobnisai, @mbasa-georepublic, @dkastl 
Are you okay about this (= @Tannybunny's) design ?

**Comment by dkastl** [comment]
I think it's a good improvement with reasonable effort to implement.

I'm not sure if we can't give users a bit more information about what is going on, for example
- add more context what `0` or other numbers mean.
- make sure that "sync" is not misunderstood as synchronization in both directions 
- indicate why "Form Notes" doesn't need to select a project

Also this design does not explain how to show "success" or "failure".

**Comment by nobnisai** [comment]
I think the current design is better with one row for each notes, but the problem is with the small screen device. The new design looks a bit confusing, but it will be good for the device with the small screen. Using the current design and changing the alignment would be great.

**Comment by sanak** [comment]
@dkastl Thanks for comment.

> I'm not sure if we can't give users a bit more information about what is going on, for example
> - add more context what 0 or other numbers mean.
> - make sure that "sync" is not misunderstood as synchronization in both directions
> - indicate why "Form Notes" doesn't need to select a project

About these, do you have some good modification text idea ?
(If not, I am thinking to create another issue for these.)

> Also this design does not explain how to show "success" or "failure".

Well, the result will be shown in next screen (same way with GSS Export), so I think that this is not a problem.

---

@nobnisai (CC: @mbasa-georepublic)  
Thanks for comment.
I am not familiar with Flutter UI things, but does Flutter support HTML responsive UI like design/layout ?
If responsive UI is supported in Flutter, then it will be the best solution as you mentioned.

**Comment by sanak** [comment]
@nobnisai, @Tannybunny (CC: @mbasa-georepublic, @dkastl)
> I am not familiar with Flutter UI things, but does Flutter support HTML responsive UI like design/layout ?
If responsive UI is supported in Flutter, then it will be the best solution as you mentioned.

About above, how about to use `Wrap` widget for each 2 columns items with fixed label width ?
Or is it just same with current wrapped label situation... ?
https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/layout-elements/wrap

### New (Wide)

<table>
  <tbody>
    <tr>
      <td colspan=2 align=left>←　　GTT Export</td>
    </tr>
    <tr>
      <td colspan=2 align=center><b>Sync Stats</b></td>
    </tr>
    <tr>
      <td colspan=2 align=left>The following data will be uploaded only if the project is <br>selected. If there is no available project, please contact <br>your admin.</td>
    </tr>
    <tr>
      <td colspan=2>Form Notes: 1</td>
    </tr>
    <tr height=10px>
      <td colspan=2></td>
    </tr>
    <tr>
      <td>Gps logs: 0</td><td align=left>Select Project　　　　　▼</td>
    </tr>
    <tr height=10px>
      <td colspan=2></td>
    </tr>
    <tr>
      <td>Simple Notes: 0</td><td align=left>Select Project　　　　　▼</td>
    </tr>
    <tr height=10px>
      <td colspan=2></td>
    </tr>
    <tr>
      <td>Images: 0</td><td align=left>Select Project　　　　　▼</td>
    </tr>
  </tbody>
</table>

### New (Narrow)

<table>
  <tbody>
    <tr>
      <td align=left>←　　GTT Export</td>
    </tr>
    <tr>
      <td align=center><b>Sync Stats</b></td>
    </tr>
    <tr>
      <td align=left>The following data will be uploaded only if the <br>project is selected. If there is no available project, <br>please contact your admin.</td>
    </tr>
    <tr>
      <td>Form Notes: 1</td>
    </tr>
    <tr height=10px>
      <td></td>
    </tr>
    <tr>
      <td>Gps logs: 0</td>
    </tr>
    <tr>
      <td align=left>Select Project　　　　　▼</td>
    </tr>
    <tr>
    </tr>
    <tr height=10px>
      <td></td>
    </tr>
    <tr>
      <td>Simple Notes: 0</td>
    </tr>
    <tr>
      <td align=left>Select Project　　　　　▼</td>
    </tr>
    <tr>
    </tr>
    <tr height=10px>
      <td></td>
    </tr>
    <tr>
      <td>Images: 0</td>
    </tr>
    <tr>
      <td align=left>Select Project　　　　　▼</td>
    </tr>
    </tr>
  </tbody>
</table>

**Comment by sanak** [comment]
@Tannybunny (CC: @dkastl)
We (@sanak, @nobnisai and @mbasa-georepublic) discuss a bit about above comment yesterday, and for consistency, above **New (Narrow)** pattern (=your design) is better than support both (wide and narrow) as responsive design, so we will modify the screen by SMASH next release.
Just FYI

**Comment by sanak** [comment]
@nobnisai, @mbasa-georepublic 
Here is the design which I created in FlutterFlow.
Do you have a time to modify the screen code in this week ?
@Tannybunny 
I forgot to add leading icon offset for each rows, so I put the offset before each select options.
![gtt-export-new](https://user-images.githubusercontent.com/629923/206939104-adcdaf9b-8114-471e-8c1c-00c0c5e767eb.png)

Some notes in the FlutterFlow:
- I couldn't find the way to set custom material design icons, so current leading icons are similar one.
- I couldn't find the way to set right-bottom floating button, so I put spacer between the last selection box and the button with horizontal layout spacing.

**Comment by Tannybunny** [comment]
Looks good, I would add a bit of padding within the main container of the screen (right and left side), maybe try 16px or something.

**Comment by sanak** [comment]
Okay, thanks for the confirmation and advice !

**Comment by sanak** [comment]
Well, this improvement is merged already in upstream with https://github.com/geopaparazzi/smash_import_export_plugins/pull/17, so I close this issue.
