### ISSUE TITLE
Match GTT Import screen UI and flow to the latest GSS (until 2022) Import screen

### ISSUE THREAD

**Issue by sanak** [gtt-project/smash_import_export_plugins#25]
**Problem**

Currently, GTT Import screen UI and flow are as follows,
<img alt="gtt-import1" src="https://user-images.githubusercontent.com/629923/206942103-22a80f75-6128-4275-8d34-d763c12be724.png" width="250px" /> => <img alt="gtt-import2" src="https://user-images.githubusercontent.com/629923/206942110-f6d1bf33-9eb8-4d61-93ee-c64d5daf31ab.png" width="250px" />

but the latest GSS (until 2022) screen UI and flows are as follows.
<img alt="gss2022-import1" src="https://user-images.githubusercontent.com/629923/206942203-0ca5995c-2f28-4e59-8c7b-4bea16e5da09.png" width="250px" /> => <img alt="gss2022-import2" src="https://user-images.githubusercontent.com/629923/206942206-a5786ebd-22c8-4b7d-a65e-e3ba9b85f6f4.png" width="250px" /> => <img alt="gss2022-import3" src="https://user-images.githubusercontent.com/629923/206942212-edd9c8ea-8cc4-4a5f-9201-6af9c66ea2ea.png" width="250px" />

**Improvement**

Match GTT Import screen UI and flow to the latest GSS (until 2022) Import screen.
- Card will be only `Forms`
- Tags file name is `gtt-tags.json`

**Alternatives**

At this moment, I don't have other alternatives idea.

**Comment by mbasa-geolonia** [comment]
why should we follow something that is just for **2022**?
